import Head from 'next/head';
import {navBar} from './layout/navbar/page';
import {heroPage} from './layout/hero/page';
export default function DefaultLayout({ children }: { children: React.ReactNode }) {
  return (
      <> 
        <Head>
          <title>Book Store</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        {navBar()}
        {heroPage()}
        <body className=" w-screen h-screen bg-gray-100 flex items-center justify-center">
          {children}
        </body>
      </>
  );
}